### PR TITLE
Add multiple country capability.

### PR DESCRIPTION
**Pull request by skorokithakis**

### CODE REVIEW

**Comment by skorokithakis** [comment]
This implements #13.

**Comment by jamiees2** [comment]
Nice, thanks! Just one quick question, any specific reason for taking in a string and splitting, instead of just argparse's [nargs](https://docs.python.org/3/library/argparse.html#nargs) ?

**Comment by skorokithakis** [comment]
The only reason is that I didn't think much about it and this came to mind (I usually use docopt). I agree that nargs would be a better solution, I can send you an updated PR later on, if you like.

**Comment by jamiees2** [comment]
Yes please, that would leave less complicated code :)

**Comment by skorokithakis** [comment]
Updated! It's pretty much the same code because of the `.lower()`, though.

**Comment by jamiees2** [comment]
Cool, thanks!

**Comment by jamiees2** [comment]
Looks good to me.

**Pull request merged**
